# Generated by Django 2.2.5 on 2020-01-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentleave',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
