# Generated by Django 2.2.5 on 2019-12-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentinfo',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='permanentAddress',
        ),
    ]
