# Generated by Django 2.2.5 on 2019-12-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20191204_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentaddress',
            old_name='admissionNumber',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='parentinfo',
            old_name='admissionNumber',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='permanentaddress',
            old_name='admissionNumber',
            new_name='student',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='fullName',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
