# Generated by Django 2.2.5 on 2019-12-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20191204_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='fName',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
