# Generated by Django 2.2.5 on 2019-12-04 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_studentinfo_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinfo',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='parent', serialize=False, to='form.StudentInfo'),
        ),
    ]
