# Generated by Django 2.2.5 on 2019-12-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20191204_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='photograph',
            new_name='photo',
        ),
    ]
