# Generated by Django 2.2.5 on 2019-12-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_auto_20191204_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentaddress',
            name='city',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
