# Generated by Django 2.2.5 on 2019-12-06 10:58

from django.db import migrations, models
import form.models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_auto_20191205_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='castCertificate',
            field=models.FileField(upload_to=form.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='documents',
            name='characterCertificate',
            field=models.FileField(upload_to=form.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='documents',
            name='domicile',
            field=models.FileField(upload_to=form.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='documents',
            name='idProof',
            field=models.FileField(upload_to=form.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='documents',
            name='photo',
            field=models.FileField(upload_to=form.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='documents',
            name='tc',
            field=models.FileField(upload_to=form.models.user_directory_path),
        ),
    ]
