# Generated by Django 2.2.5 on 2019-12-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_auto_20191206_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentinfo',
            name='gaurdianName',
        ),
    ]
