# Generated by Django 2.2.5 on 2020-01-18 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_auto_20191225_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRoute',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='form.StudentInfo')),
                ('route_code', models.BigIntegerField()),
                ('route_stoppage', models.CharField(max_length=30)),
                ('shift', models.CharField(max_length=30)),
            ],
        ),
    ]
