# Generated by Django 2.2.5 on 2020-01-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_studentroute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentRoute',
        ),
    ]
