# Generated by Django 2.2.5 on 2020-02-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0017_auto_20200130_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='siblingID0',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='siblingID1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='siblingID2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
