# Generated by Django 2.2.5 on 2020-02-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0018_auto_20200204_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
