# Generated by Django 2.2.5 on 2019-12-06 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('fullName', models.CharField(max_length=50)),
                ('fatherName', models.CharField(max_length=50)),
                ('motherName', models.CharField(max_length=50)),
                ('partnerName', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('currentAddress', models.CharField(max_length=100)),
                ('permanentAddress', models.CharField(max_length=100)),
                ('dob', models.DateField(null=True)),
                ('joiningDate', models.DateField(null=True)),
                ('bloodGroup', models.CharField(max_length=20)),
                ('mobileNumber', models.BigIntegerField(default=0)),
                ('maritalStatus', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
                ('aadharNumber', models.BigIntegerField(default=0)),
                ('empCategory', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocuments',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employeeform.Employee')),
                ('photo', models.FileField(upload_to='uploads/emp/photograph')),
                ('qualificationDoc', models.FileField(upload_to='uploads/emp/qualificationDocs')),
                ('idProof', models.FileField(upload_to='uploads/emp/idProof')),
                ('addressProof', models.FileField(upload_to='uploads/emp/addressProof')),
                ('otherDoc', models.FileField(upload_to='uploads/emp/otherDoc')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employeeform.Employee')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('fullName', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('classTeacher', models.CharField(max_length=50)),
            ],
        ),
    ]
