# Generated by Django 2.2.5 on 2019-12-06 10:49

from django.db import migrations, models
import employeeform.models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeform', '0002_currentaddress_permanentaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocuments',
            name='addressProof',
            field=models.FileField(upload_to=employeeform.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocuments',
            name='idProof',
            field=models.FileField(upload_to=employeeform.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocuments',
            name='otherDoc',
            field=models.FileField(upload_to=employeeform.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocuments',
            name='photo',
            field=models.FileField(upload_to=employeeform.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='employeedocuments',
            name='qualificationDoc',
            field=models.FileField(upload_to=employeeform.models.user_directory_path),
        ),
    ]
