# Generated by Django 2.2.5 on 2019-12-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeform', '0003_auto_20191206_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedocuments',
            old_name='idProof',
            new_name='IdProof',
        ),
    ]
