# Generated by Django 2.2.5 on 2019-12-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeform', '0004_auto_20191206_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fatherName',
            new_name='father_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='maritalStatus',
            new_name='marital_status',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='mobileNumber',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='motherName',
            new_name='mother_name',
        ),
    ]
