# Generated by Django 2.2.5 on 2020-02-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeform', '0007_auto_20200130_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='lastName',
        ),
    ]
