# Generated by Django 2.2.5 on 2020-02-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeform', '0008_auto_20200201_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
