# Generated by Django 2.2.5 on 2020-02-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeform', '0009_employee_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='deleted',
        ),
    ]
