# Generated by Django 2.2.5 on 2019-12-21 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classform', '0004_auto_20191210_0011'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feediscount',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classform.ClassRoomStudent'),
            preserve_default=False,
        ),
    ]
