# Generated by Django 2.2.5 on 2019-12-24 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_auto_20191221_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='submissionDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
