# Generated by Django 2.2.5 on 2019-12-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_auto_20191221_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='submissionDate',
            field=models.DateField(null=True),
        ),
    ]
