# Generated by Django 2.2.5 on 2020-01-11 18:02

from django.db import migrations, models
import fees.models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_fine_submissiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='feeSlip',
            field=models.FileField(default='', upload_to=fees.models.user_directory_path),
            preserve_default=False,
        ),
    ]
