# Generated by Django 2.2.5 on 2019-12-20 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20191219_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='date',
            field=models.DateField(default=datetime.date(2019, 12, 20)),
        ),
    ]
