# Generated by Django 2.2.5 on 2019-12-21 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_auto_20191221_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
