# Generated by Django 2.2.5 on 2019-12-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_auto_20191221_2047'),
        ('newsletter', '0005_auto_20191221_1512'),
    ]

    operations = [
    ]
