# Generated by Django 2.2.5 on 2019-12-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_auto_20191223_1057'),
        ('newsletter', '0008_auto_20191224_1320'),
    ]

    operations = [
    ]
