# Generated by Django 2.2.7 on 2019-12-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_no',
            field=models.BigIntegerField(default=0),
        ),
    ]
