# Generated by Django 2.2.5 on 2019-12-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191224_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fullName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
