# Generated by Django 2.2.5 on 2020-01-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200122_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='addmission_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emp_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
