# Generated by Django 2.2.5 on 2019-12-13 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classform', '0004_auto_20191210_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examName', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examType', models.CharField(max_length=50)),
                ('minMarks', models.IntegerField(default=0)),
                ('maxMarks', models.IntegerField()),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('examName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markssection.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('marks', models.IntegerField()),
                ('classroomStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classform.ClassRoomStudent')),
                ('examType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markssection.ExamType')),
            ],
        ),
        migrations.CreateModel(
            name='ExamMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classform.ClassRoom')),
                ('examName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markssection.Exam')),
                ('examType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markssection.ExamType')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('marks', models.IntegerField(default=0)),
                ('classroomStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classform.ClassRoomStudent')),
            ],
        ),
    ]
