# Generated by Django 2.2.5 on 2019-12-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markssection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='examName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='markssection.Exam'),
            preserve_default=False,
        ),
    ]
