# Generated by Django 2.2.5 on 2019-12-18 08:52

from django.db import migrations, models
import django.db.models.deletion
import notice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classform', '0004_auto_20191210_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.TextField()),
                ('notice_document', models.FileField(blank=True, upload_to=notice.models.student_directory_path)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classform.ClassRoomStudent')),
            ],
        ),
        migrations.CreateModel(
            name='ClassNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.TextField()),
                ('notice_document', models.FileField(blank=True, upload_to=notice.models.user_directory_path)),
                ('classRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classform.ClassRoom')),
            ],
        ),
    ]
