# Generated by Django 2.2.5 on 2020-02-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroomsubjectteacher',
            old_name='subjects',
            new_name='subject',
        ),
    ]
