# Generated by Django 2.2.5 on 2019-12-07 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employeeform', '0004_auto_20191206_1630'),
        ('form', '0010_auto_20191206_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classSection', models.CharField(max_length=50)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employeeform.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoomStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.IntegerField()),
                ('classRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classform.ClassRoom')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form.StudentInfo')),
            ],
        ),
    ]
