# Generated by Django 2.2.5 on 2019-12-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroomstudent',
            old_name='rollNumber',
            new_name='roll_number',
        ),
    ]
