# Generated by Django 2.2.5 on 2019-12-09 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classform', '0002_auto_20191209_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroomstudent',
            old_name='roll_number',
            new_name='rollNumber',
        ),
    ]
