# Generated by Django 2.2.5 on 2019-12-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classform', '0003_auto_20191210_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroomstudent',
            old_name='rollNumber',
            new_name='roll_number',
        ),
    ]
