# Generated by Django 2.2.5 on 2020-01-12 07:24

import classform.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classform', '0004_auto_20191210_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportCard', models.FileField(upload_to=classform.models.user_directory_path)),
                ('class_room_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classform.ClassRoomStudent')),
            ],
        ),
    ]
