# Generated by Django 2.2.5 on 2020-01-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classform', '0008_auto_20200131_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_teacher_alloted',
            field=models.BooleanField(default=False),
        ),
    ]
