# Generated by Django 2.2.5 on 2020-02-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classform', '0009_classroom_class_teacher_alloted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
        migrations.AddField(
            model_name='classroom',
            name='_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='classroom',
            name='_section',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='classroom',
            name='room_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
