# Generated by Django 2.2.5 on 2020-01-23 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_auto_20200123_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 0, 25, 3, 906239)),
        ),
    ]
