# Generated by Django 2.2.5 on 2020-01-23 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_auto_20200124_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 0, 49, 31, 61889)),
        ),
    ]
