# Generated by Django 2.2.5 on 2020-01-25 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0007_auto_20200124_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 25, 11, 55, 29, 255645)),
        ),
    ]
