# Generated by Django 2.2.5 on 2020-01-25 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0009_auto_20200125_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 25, 12, 0, 18, 258651)),
        ),
    ]
