# Generated by Django 2.2.5 on 2020-01-29 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0013_auto_20200130_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 1, 18, 57, 118834)),
        ),
    ]
