# Generated by Django 2.2.5 on 2020-01-29 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0014_auto_20200130_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 1, 35, 40, 839817)),
        ),
    ]
