# Generated by Django 2.2.5 on 2019-12-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_auto_20191210_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendence',
            name='available_casual_leave',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherattendence',
            name='available_sick_leave',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherattendence',
            name='taken_casual_leave',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherattendence',
            name='taken_sick_leave',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherattendence',
            name='total_no_of_days_present',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
