# Generated by Django 2.2.5 on 2019-12-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0003_auto_20191210_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherattendence',
            name='available_casual_leave',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='teacherattendence',
            name='available_sick_leave',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='teacherattendence',
            name='taken_casual_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacherattendence',
            name='taken_sick_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacherattendence',
            name='total_no_of_days_present',
            field=models.IntegerField(default=0),
        ),
    ]
