# Generated by Django 2.2.5 on 2020-01-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_vehicle_service_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routes',
            old_name='rout_code',
            new_name='route_code',
        ),
    ]
