# Generated by Django 2.2.5 on 2020-01-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_auto_20200118_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='lattitude',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='routes',
            name='longitude',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
