# Generated by Django 2.2.5 on 2020-01-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_auto_20200127_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='stoppage_names',
            field=models.CharField(default='', max_length=100),
        ),
    ]
