# Generated by Django 2.2.5 on 2019-12-19 10:34

from django.db import migrations, models
import schoolinfo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('schoolName', models.CharField(max_length=100)),
                ('addresss', models.CharField(max_length=100)),
                ('principalName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipCode', models.IntegerField(max_length=100)),
                ('schoolID', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('longitude', models.IntegerField(max_length=100)),
                ('latitude', models.IntegerField(max_length=100)),
                ('contactNumber', models.IntegerField(max_length=100)),
                ('webSiteURL', models.CharField(max_length=100)),
                ('img', models.FileField(upload_to=schoolinfo.models.user_directory_path)),
                ('logo', models.FileField(upload_to=schoolinfo.models.user_directory_path)),
            ],
        ),
    ]
